import type { ClimatePackage } from "./types";

/** Bundled climate-package core, sourced from each repo's CITATION.cff.
 *  Live GitHub fetch overlays this; it is not a universal equation. */
export const SEED_PACKAGES: ClimatePackage[] = [
  {
    name: "amoc-utac",
    title: "amoc-utac — Atlantic Meridional Overturning Circulation Collapse Early Warning",
    packageNumber: 18,
    version: "1.3.0",
    released: "2026-08-02",
    license: "MIT",
    branch: "main",
    abstract: "GenesisAeon Package 18. Models the Atlantic Meridional Overturning Circulation (AMOC) as a UTAC dynamical system with CREP tensor coupling. Central result: Γ_AMOC = arctanh(η=0.50) / σ=2.2 ≈ 0.251, placing AMOC in the medium-CREP regime and establishing cross-domain universality with neural criticality (Package 20) at the 50% homeostatic efficiency setpoint.",
    keywords: ["AMOC", "tipping point", "UTAC", "CREP", "ocean circulation", "GenesisAeon", "early warning signal", "critical slowing down"],
    dois: ["10.1126/sciadv.adk1189", "10.1038/s41467-023-39810-w"],
    selfDoi: "10.5281/zenodo.21432660",
    themes: ["ozean", "extreme"] as ClimatePackage["themes"],
    noUtacBridge: false,
    htmlUrl: "https://github.com/GenesisAeon/amoc-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/amoc-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/amoc-utac/main/README.md",
  },
  {
    name: "amazon-utac",
    title: "amazon-utac: Amazon Rainforest Savannisation Threshold UTAC Model",
    packageNumber: 19,
    version: "0.1.0",
    released: "2026-04-23",
    license: "MIT",
    branch: "main",
    abstract: "GenesisAeon Package 19. Models the Amazon rainforest → savanna tipping transition as a UTAC dynamical system with a double-well potential landscape. Implements the CREP tensor (C, R, E, P) calibrated against Lovejoy & Nobre (2019) and Boulton et al. (2022). Central result: Γ_Amazon ≈ 0.116 (LOW-CREP zone). Includes Ethics-Gate Light (Phase H) for responsible scientific output.",
    keywords: ["amazon", "deforestation", "tipping point", "savannisation", "UTAC", "CREP", "GenesisAeon", "forest resilience", "critical slowing down"],
    dois: ["10.1126/sciadv.aba2949", "10.1038/s41558-022-01287-8", "10.5281/zenodo.5831935"],
    selfDoi: "10.5281/zenodo.20746954",
    themes: ["ozean", "biosphaere", "extreme"] as ClimatePackage["themes"],
    noUtacBridge: false,
    htmlUrl: "https://github.com/GenesisAeon/amazon-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/amazon-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/amazon-utac/main/README.md",
  },
  {
    name: "carbon-sinks-utac",
    title: "carbon-sinks-utac",
    packageNumber: 59,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Combines the real 2025 ocean CO2-uptake upward correction and the real 2026 land carbon-sink downward correction into a net picture, plus a SPECULATIVE UTAC/CREP sink-stress bridge. GenesisAeon P59.",
    keywords: ["GenesisAeon", "P59", "UTAC", "CREP", "carbon-cycle", "carbon-sinks", "climate", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["ozean", "kohlenstoff"] as ClimatePackage["themes"],
    noUtacBridge: false,
    htmlUrl: "https://github.com/GenesisAeon/carbon-sinks-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/carbon-sinks-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/carbon-sinks-utac/main/README.md",
  },
  {
    name: "permafrost-utac",
    title: "permafrost-utac",
    packageNumber: 60,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real ESA CCI Permafrost v5.0 data and Schuur et al. 2022 carbon-stock science -- deliberately no UTAC/CREP/AFET bridge, per climate-topic convention. GenesisAeon P60.",
    keywords: ["GenesisAeon", "P60", "permafrost", "climate", "ESA-CCI", "carbon-feedback", "open-science"],
    dois: ["10.5285/a6fbedd8ee5b472c8e84e55f746c1704"],
    selfDoi: null,
    themes: ["kryosphaere", "kohlenstoff"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/permafrost-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/permafrost-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/permafrost-utac/main/README.md",
  },
  {
    name: "climate-dashboard",
    title: "climate-dashboard",
    packageNumber: 82,
    version: "1.0.0",
    released: "2026-03-26",
    license: "GPL-3.0-or-later",
    branch: "main",
    abstract: "Interactive Climate Entropy Dashboard for the GenesisAeon stack - visualizes duality, modulation, UTAC thresholds, mandala resonance and sonification output.",
    keywords: ["GenesisAeon", "UTAC", "CREP", "open-science", "climate", "entropy", "dashboard", "visualization", "P82"],
    dois: [],
    selfDoi: null,
    themes: ["atmosphaere"] as ClimatePackage["themes"],
    noUtacBridge: false,
    htmlUrl: "https://github.com/GenesisAeon/climate-dashboard",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/climate-dashboard/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/climate-dashboard/main/README.md",
  },
  {
    name: "cascading-tipping-utac",
    title: "cascading-tipping-utac",
    packageNumber: 87,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real Wunderling et al. tipping-element interaction network (Greenland/WAIS/AMOC/Amazon) -- deliberately no UTAC/CREP/AFET bridge beyond the real published network model. GenesisAeon P87.",
    keywords: ["GenesisAeon", "P87", "climate", "tipping-points", "cascading-tipping-points", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["ozean", "biosphaere", "extreme"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/cascading-tipping-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/cascading-tipping-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/cascading-tipping-utac/main/README.md",
  },
  {
    name: "aerosol-masking-utac",
    title: "aerosol-masking-utac",
    packageNumber: 88,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real aerosol-masking / shipping-sulfur unmasking science (IMO 2020) -- deliberately no UTAC/CREP/AFET bridge, honest spread of estimates + a relativizing null-result study included. GenesisAeon P88.",
    keywords: ["GenesisAeon", "P88", "climate", "aerosols", "shipping-emissions", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["atmosphaere"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/aerosol-masking-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/aerosol-masking-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/aerosol-masking-utac/main/README.md",
  },
  {
    name: "cloud-feedback-utac",
    title: "cloud-feedback-utac",
    packageNumber: 89,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real cloud-feedback / climate-sensitivity science (Myers et al. 2021, Tan et al. 2025) -- deliberately no UTAC/CREP/AFET bridge, honest presentation of an active scientific disagreement. GenesisAeon P89.",
    keywords: ["GenesisAeon", "P89", "climate", "cloud-feedback", "climate-sensitivity", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["atmosphaere"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/cloud-feedback-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/cloud-feedback-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/cloud-feedback-utac/main/README.md",
  },
  {
    name: "soil-moisture-utac",
    title: "soil-moisture-utac",
    packageNumber: 90,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real critical soil moisture threshold science (Fu et al. 2024, Qiao et al. 2023) -- deliberately no UTAC/CREP/AFET bridge. GenesisAeon P90.",
    keywords: ["GenesisAeon", "P90", "climate", "soil-moisture", "land-atmosphere-feedback", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["hydrologie"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/soil-moisture-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/soil-moisture-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/soil-moisture-utac/main/README.md",
  },
  {
    name: "vegetation-state-utac",
    title: "vegetation-state-utac",
    packageNumber: 91,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real vegetation drought-stress and hydraulic-failure mortality science (Choat 2012, Adams 2017, Gazol 2025) -- deliberately no UTAC/CREP/AFET bridge. GenesisAeon P91.",
    keywords: ["GenesisAeon", "P91", "climate", "vegetation", "drought-mortality", "hydraulic-failure", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["biosphaere"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/vegetation-state-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/vegetation-state-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/vegetation-state-utac/main/README.md",
  },
  {
    name: "methane-hydrates-utac",
    title: "methane-hydrates-utac",
    packageNumber: 92,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real methane hydrate destabilization science (Ruppel & Kessler 2017, Hong et al. 2017) -- slow centuries-scale carbon store, explicitly NOT clathrate-gun alarmism, no UTAC/CREP/AFET bridge. GenesisAeon P92.",
    keywords: ["GenesisAeon", "P92", "climate", "methane-hydrates", "permafrost", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["kryosphaere", "atmosphaere", "kohlenstoff"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/methane-hydrates-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/methane-hydrates-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/methane-hydrates-utac/main/README.md",
  },
  {
    name: "ocean-deoxygenation-utac",
    title: "ocean-deoxygenation-utac",
    packageNumber: 93,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real ocean deoxygenation science (Schmidtko 2017, Breitburg 2018, Oschlies 2021) -- deliberately no UTAC/CREP/AFET bridge. GenesisAeon P93.",
    keywords: ["GenesisAeon", "P93", "climate", "ocean-deoxygenation", "oxygen-minimum-zones", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["ozean"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/ocean-deoxygenation-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/ocean-deoxygenation-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/ocean-deoxygenation-utac/main/README.md",
  },
  {
    name: "extreme-vs-mean-utac",
    title: "extreme-vs-mean-utac",
    packageNumber: 94,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real extreme-event-vs-mean-statistics climate science (Patterson 2023, Ballester 2023) -- deliberately no UTAC/CREP/AFET bridge. GenesisAeon P94.",
    keywords: ["GenesisAeon", "P94", "climate", "extreme-events", "heat-mortality", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["extreme"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/extreme-vs-mean-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/extreme-vs-mean-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/extreme-vs-mean-utac/main/README.md",
  },
  {
    name: "adaptation-resilience-utac",
    title: "adaptation-resilience-utac",
    packageNumber: 95,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real climate adaptation cost-benefit science (Reguero 2018, Global Commission on Adaptation 2019) -- deliberately no UTAC/CREP/AFET bridge. GenesisAeon P95.",
    keywords: ["GenesisAeon", "P95", "climate", "adaptation", "resilience", "cost-benefit", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["gesellschaft"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/adaptation-resilience-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/adaptation-resilience-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/adaptation-resilience-utac/main/README.md",
  },
  {
    name: "socioeconomic-feedback-utac",
    title: "socioeconomic-feedback-utac",
    packageNumber: 96,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real climate-socioeconomic feedback science (Burke 2015, Cattaneo 2024) -- deliberately no UTAC/CREP/AFET bridge, deliberately avoids the retracted Kotz/Levermann/Wenz 2024 Nature paper. GenesisAeon P96.",
    keywords: ["GenesisAeon", "P96", "climate", "socioeconomic", "migration", "economics", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["gesellschaft"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/socioeconomic-feedback-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/socioeconomic-feedback-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/socioeconomic-feedback-utac/main/README.md",
  },
  {
    name: "glacier-buffer-utac",
    title: "glacier-buffer-utac",
    packageNumber: 99,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Real glacial hydrological buffer (peak water) and downstream buffer-loss cascade science -- deliberately no UTAC/CREP/AFET bridge. GenesisAeon P99.",
    keywords: ["GenesisAeon", "P99", "climate", "glacier", "peak-water", "hydrology", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["kryosphaere", "hydrologie"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/glacier-buffer-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/glacier-buffer-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/glacier-buffer-utac/master/README.md",
  },
  {
    name: "glacier-buffer-replacement-utac",
    title: "glacier-buffer-replacement-utac",
    packageNumber: 100,
    version: "1.1.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Artificial Glacier Buffer Replacement (AGBR) science -- proglacial reservoirs, sedimentation limits, Managed Aquifer Recharge, floating-solar evaporation mitigation, and the real mass-balance ceiling on full replacement (Farinotti et al. 2016), plus a clearly-flagged speculative Resilience Replacement Factor / scenario layer. Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P100, companion to glacier-buffer-utac (P99).",
    keywords: ["GenesisAeon", "P100", "climate", "glacier", "hydrology", "managed-aquifer-recharge", "floating-solar", "open-science"],
    dois: ["10.1088/1748-9326/11/5/054022", "10.5194/esurf-10-723-2022", "10.1186/s00015-021-00399-1", "10.1038/s41893-019-0307-1", "10.1016/j.scitotenv.2022.153937", "10.1038/s41893-023-01089-6", "10.1080/02626667.2024.2332625"],
    selfDoi: null,
    themes: ["kryosphaere", "hydrologie"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/glacier-buffer-replacement-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/glacier-buffer-replacement-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/glacier-buffer-replacement-utac/master/README.md",
  },
  {
    name: "glacial-seismicity-utac",
    title: "glacial-seismicity-utac",
    packageNumber: 101,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Glacial Isostatic Adjustment (GIA) and glacially-induced/modulated seismicity: Coulomb Failure Stress mechanics, historic deglaciation fault reactivation (Parvie Fault, Charlevoix), and modern glacier-retreat seismicity modulation (Alaska/Fairweather Fault, Mont Blanc massif, eastern North America), with two numbers independently corrected after verification against the source papers. Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P101.",
    keywords: ["GenesisAeon", "P101", "climate", "glacier", "seismology", "glacial-isostatic-adjustment", "open-science"],
    dois: ["10.5194/se-6-621-2015", "10.1785/0120100190", "10.1029/2022GL100276", "10.1029/2020JB020411", "10.1016/j.epsl.2025.119372", "10.1029/2025GC012290"],
    selfDoi: null,
    themes: ["kryosphaere"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/glacial-seismicity-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/glacial-seismicity-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/glacial-seismicity-utac/master/README.md",
  },
  {
    name: "paraglacial-hazard-utac",
    title: "paraglacial-hazard-utac",
    packageNumber: 102,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Paraglacial and geophysical hazard science: GIA/seismicity context (a real Western Alps contrast case), permafrost-driven rock-slope instability, and glacial lake outburst flood (GLOF) exposure. Companion to glacial-seismicity-utac (P101). Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P102.",
    keywords: ["GenesisAeon", "P102", "climate", "glacier", "geohazard", "permafrost", "GLOF", "open-science"],
    dois: ["10.5194/se-14-1067-2023", "10.1016/S0277-3791(02)00005-7", "10.1002/esp.70063", "10.1029/2006JF000547", "10.1038/s41467-023-36033-x", "10.5194/essd-15-2983-2023"],
    selfDoi: null,
    themes: ["kryosphaere", "hydrologie", "extreme", "kohlenstoff"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/paraglacial-hazard-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/paraglacial-hazard-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/paraglacial-hazard-utac/master/README.md",
  },
  {
    name: "distributed-buffer-resilience-utac",
    title: "distributed-buffer-resilience-utac",
    packageNumber: 103,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Distributed hydrological/ecosystem buffer resilience for deglacierizing catchments: van Tiel et al. 2026's drought-buffer evidence, Farinotti et al. 2016/2019's storage-portfolio figures, Immerzeel/Pritchard water-tower science, Casallas et al. 2025 ecosystem-service trade-offs, plus a clearly-flagged speculative Glacier Buffer Replacement score. Companion to glacier-buffer-utac (P99) and glacier-buffer-replacement-utac (P100). Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P103.",
    keywords: ["GenesisAeon", "P103", "climate", "glacier", "hydrology", "ecosystem-services", "water-towers", "open-science"],
    dois: ["10.5194/hess-30-23-2026", "10.1088/1748-9326/11/5/054022", "10.1038/s41586-019-1740-z", "10.1038/s41558-017-0049-x", "10.1038/nature22062", "10.1038/s41586-019-1822-y", "10.1016/j.ecoser.2025.101730"],
    selfDoi: null,
    themes: ["kryosphaere", "biosphaere", "hydrologie"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/distributed-buffer-resilience-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/distributed-buffer-resilience-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/distributed-buffer-resilience-utac/master/README.md",
  },
  {
    name: "mountain-governance-adaptation-utac",
    title: "mountain-governance-adaptation-utac",
    packageNumber: 104,
    version: "1.0.0",
    released: "2026-08-15",
    license: "MIT",
    branch: "master",
    abstract: "Mountain water governance and adaptation science: real transboundary treaty status (Indus Waters Treaty, Colorado River Compact, Mekong Agreement), the mountain-specific adaptation finance gap, and Loss & Damage institutions (FRLD, WIM ExCom Non-Economic Losses framework). Documents real institutions only -- no simulated governance dynamics, no personal testimony encoded as data. Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P104, the governance/institutional closing chapter of the P99-P103 series.",
    keywords: ["GenesisAeon", "P104", "climate", "water-governance", "adaptation", "loss-and-damage", "open-science"],
    dois: [],
    selfDoi: null,
    themes: ["hydrologie", "gesellschaft"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/mountain-governance-adaptation-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/mountain-governance-adaptation-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/mountain-governance-adaptation-utac/master/README.md",
  },
  {
    name: "black-carbon-albedo-utac",
    title: "black-carbon-albedo-utac",
    packageNumber: 105,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Black carbon / light-absorbing-particle albedo feedback on glaciers: Kang et al. 2020's mechanism review, Li et al. 2017's Central Tibetan Plateau melt-enhancement case, and Yang, Kang, Chen et al. 2025's plateau-wide solid-water-storage decline study. A new atmospheric-deposition lens on the P99-P104 series, contrasting aerosol-masking-utac's global cooling effect. Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P105.",
    keywords: ["GenesisAeon", "P105", "climate", "glacier", "black-carbon", "albedo", "open-science"],
    dois: ["10.1016/j.earscirev.2020.103346", "10.1016/j.scitotenv.2017.02.169", "10.1038/s43247-025-02335-9"],
    selfDoi: null,
    themes: ["kryosphaere", "atmosphaere", "hydrologie", "kohlenstoff"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/black-carbon-albedo-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/black-carbon-albedo-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/black-carbon-albedo-utac/master/README.md",
  },
  {
    name: "freshwater-ecosystem-stressors-utac",
    title: "freshwater-ecosystem-stressors-utac",
    packageNumber: 106,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Freshwater ecosystem stressors under deglacierization: WWF Living Planet Report 2022's freshwater biodiversity decline, Ramsar Global Wetland Outlook's wetland loss, and the 2022 Oder/Odra River multi-stressor disaster case study. The ecological bridge between the P99-P102 physical series and the P103-P104 resilience/governance series. Deliberately excludes time-bound current-conditions data (river-level readings, seasonal forecasts) as unsuitable for a versioned science package. Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P106.",
    keywords: ["GenesisAeon", "P106", "climate", "freshwater-ecology", "biodiversity", "wetlands", "open-science"],
    dois: ["10.3390/toxins15060403"],
    selfDoi: null,
    themes: ["kryosphaere", "biosphaere", "hydrologie", "gesellschaft"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/freshwater-ecosystem-stressors-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/freshwater-ecosystem-stressors-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/freshwater-ecosystem-stressors-utac/master/README.md",
  },
  {
    name: "landscape-restoration-hydrology-utac",
    title: "landscape-restoration-hydrology-utac",
    packageNumber: 107,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Landscape restoration hydrology: the Murg/Rastatt floodplain reconnection case study, Umer et al. 2025's Kitwe (Zambia) nature-based-solutions modeling, German drained-peatland emissions, and Pavlidis & Tsihrintzis 2018's agroforestry/hedgerow water-quality review. Extends the P99/P103 distributed-buffer series with real restoration-effectiveness evidence. Deliberately excludes German funding-program/legal/cost data as unsuitable for a science package. Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P107.",
    keywords: ["GenesisAeon", "P107", "climate", "hydrology", "restoration", "agroforestry", "peatland", "open-science"],
    dois: ["10.1007/s11269-017-1805-4"],
    selfDoi: null,
    themes: ["biosphaere", "hydrologie", "extreme"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/landscape-restoration-hydrology-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/landscape-restoration-hydrology-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/landscape-restoration-hydrology-utac/master/README.md",
  },
  {
    name: "urban-green-infrastructure-utac",
    title: "urban-green-infrastructure-utac",
    packageNumber: 108,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Urban green infrastructure hydrology: soil sealing and groundwater recharge (Grischek et al. 1996, replacing an unverifiable statistic caught during verification), green roof stormwater retention (Zheng et al. 2021, Gregoire & Clausen 2011). Companion to landscape-restoration-hydrology-utac (P107), the urban physical setting. Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P108.",
    keywords: ["GenesisAeon", "P108", "climate", "urban-hydrology", "green-roofs", "soil-sealing", "open-science"],
    dois: ["10.1016/j.resconrec.2021.105577"],
    selfDoi: null,
    themes: ["hydrologie", "gesellschaft"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/urban-green-infrastructure-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/urban-green-infrastructure-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/urban-green-infrastructure-utac/master/README.md",
  },
  {
    name: "glacier-legacy-contaminants-utac",
    title: "glacier-legacy-contaminants-utac",
    packageNumber: 109,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Glaciers as chemical archives: Pawlak et al. 2021's 'cold condenser' deposition mechanism review, Bogdal et al. 2009's real Lake Oberaar (Switzerland) contaminant-release case study, and McGovern et al. 2022's Arctic food-web complication. Bridges glacier-buffer-utac (P99), black-carbon-albedo-utac (P105), and freshwater-ecosystem-stressors-utac (P106). Deliberately includes a finding that complicates its own headline narrative. Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P109.",
    keywords: ["GenesisAeon", "P109", "climate", "glacier", "persistent-organic-pollutants", "environmental-chemistry", "open-science"],
    dois: ["10.1016/j.scitotenv.2021.145244", "10.1021/es901628x", "10.1021/acs.est.1c07062"],
    selfDoi: null,
    themes: ["kryosphaere", "biosphaere", "hydrologie", "kohlenstoff"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/glacier-legacy-contaminants-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/glacier-legacy-contaminants-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/glacier-legacy-contaminants-utac/master/README.md",
  },
  {
    name: "snowpack-elevation-warming-utac",
    title: "snowpack-elevation-warming-utac",
    packageNumber: 110,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "The seasonal snow buffer is eroding: Pepin et al. 2015's elevation-dependent-warming mechanism review, Matiu et al. 2021's European Alps snow depth trends (1971-2019), Notarnicola 2022's global mountain snow cover trends (1982-2020, incl. the Karakoram anomaly and winter/spring divergence), and Mote et al. 2018's western US snowpack decline (since 1915). Quantifies distributed-buffer-resilience-utac's (P103) unquantified 'snow (seasonal)' buffer category and extends glacier-buffer-utac's (P99) peak-water framing. Deliberately includes findings that complicate its own headline narrative. Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P110.",
    keywords: ["GenesisAeon", "P110", "climate", "snowpack", "cryosphere", "elevation-dependent-warming", "open-science"],
    dois: ["10.1038/nclimate2563", "10.5194/tc-15-1343-2021", "10.1038/s41598-022-16743-w", "10.1038/s41612-018-0012-1"],
    selfDoi: null,
    themes: ["kryosphaere", "hydrologie"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/snowpack-elevation-warming-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/snowpack-elevation-warming-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/snowpack-elevation-warming-utac/master/README.md",
  },
  {
    name: "climate-disease-attribution-utac",
    title: "climate-disease-attribution-utac",
    packageNumber: 111,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Climate-attributable disease burden: WHO 2024 dengue/cholera surveillance, PNAS 2025 dengue climate-warming attribution (Childs/Lyberger/Harris/Burke/Mordecai et al., 18% CI 11-27%), Reyburn et al. 2011's Zanzibar cholera-temperature time series, Lancet Countdown 2025 heat mortality (Romanello/Walawender et al., 546,000 deaths/yr, 63% rate increase since 1990s), and Mora et al. 2022's cross-cutting pathogen climate-sensitivity synthesis. Independently re-verified from a research report after finding its in-text citation links were systematically mismatched; includes a real correction of that report's own numbers. Deliberately excludes climate-migration causality, funding/legal/policy content, and time-bound outbreak snapshots. Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P111.",
    keywords: ["GenesisAeon", "P111", "climate", "epidemiology", "disease-attribution", "public-health", "open-science"],
    dois: ["10.1073/pnas.2512350122", "10.4269/ajtmh.2011.10-0277", "10.1016/S0140-6736(25)01919-1", "10.1038/s41558-022-01426-1"],
    selfDoi: null,
    themes: ["atmosphaere", "gesellschaft"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/climate-disease-attribution-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/climate-disease-attribution-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/climate-disease-attribution-utac/master/README.md",
  },
  {
    name: "multi-purpose-water-storage-utac",
    title: "multi-purpose-water-storage-utac",
    packageNumber: 112,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Can one basin do it all? Pit Thermal Energy Storage (Xiang et al. 2022, Vojens seasonal + Hoeje Taastrup weekly cycles), Aquifer Thermal Energy Storage (Dutch deployment scale, 2800-3500+ systems), reservoir-supplied wetland environmental flow (Akbarichegeni & Yosefvand 2026, a modeling study), and navigation-weir/wetland connectivity (Hein et al. 2016's real Danube data, -68% floodplain loss vs pre-regulation) -- then honestly documents that no literature-demonstrated case integrates all of them in one structure. Deliberately includes a finding that complicates its own motivating question. No UTAC/CREP/AFET bridge. GenesisAeon P112.",
    keywords: ["GenesisAeon", "P112", "climate", "thermal-energy-storage", "water-management", "wetland-restoration", "open-science"],
    dois: ["10.1016/j.est.2022.105716", "10.1016/j.scitotenv.2015.09.073"],
    selfDoi: null,
    themes: ["biosphaere", "hydrologie", "extreme"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/multi-purpose-water-storage-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/multi-purpose-water-storage-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/multi-purpose-water-storage-utac/master/README.md",
  },
  {
    name: "mixed-forest-resilience-utac",
    title: "mixed-forest-resilience-utac",
    packageNumber: 113,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Why structurally diverse forests outperform monocultures: Pretzsch & Schuetze 2009 (mixed-stand overyielding up to 59%, site-dependent), Jactel & Brockerhoff 2007 (associational resistance, 119-study meta-analysis), Jactel/Scherer-Lorenzen et al. 2025 (real MyDiv bark-beetle field evidence, Germany), Bosela et al. 2025 (drought/carbon resilience, 24-yr Slovakia paired comparison), and Obladen et al. 2021 (the honesty check: beech also dies in drought, ~7% vs spruce's ~50%, just far less). Deliberately includes a finding that complicates its own headline narrative. No UTAC/CREP/AFET bridge. GenesisAeon P113.",
    keywords: ["GenesisAeon", "P113", "climate", "forestry", "mixed-forest", "forest-resilience", "open-science"],
    dois: ["10.1007/s10342-008-0215-9", "10.1111/j.1461-0248.2007.01073.x", "10.1007/s10340-025-01995-y", "10.1016/j.foreco.2025.122829", "10.1016/j.agrformet.2021.108482"],
    selfDoi: null,
    themes: ["biosphaere", "kohlenstoff"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/mixed-forest-resilience-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/mixed-forest-resilience-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/mixed-forest-resilience-utac/master/README.md",
  },
  {
    name: "coral-reef-utac",
    title: "coral-reef-utac",
    packageNumber: 114,
    version: "1.1.0",
    released: "2026-09-02",
    license: "MIT",
    branch: "master",
    abstract: "NOAA Coral Reef Watch's real, official Degree Heating Week (DHW) coral-bleaching threshold system (0-20C-weeks, 5 alert levels), the real escalating series of four documented global bleaching events (Hughes et al. 2017/2018, NOAA 2024: 21% -> 37% -> 68% -> 83.7% of reef area affected), a real thermal-acidification synergy (Guillermic et al. 2021: heat disables corals' acidification-coping mechanism), and Walker et al. 2023 (the honesty check: bleaching resistance varies by genotype with real fitness tradeoffs). Deliberately no UTAC/CREP/AFET bridge and no invented Gamma value -- see DISCLAIMER.md. GenesisAeon P114.",
    keywords: ["GenesisAeon", "P114", "climate", "coral-reef", "ocean", "bleaching", "open-science"],
    dois: ["10.1038/nature21707", "10.1126/science.aan8048", "10.1126/sciadv.aba9958", "10.1111/eva.13500", "10.59387/LFPR6347"],
    selfDoi: null,
    themes: ["ozean", "biosphaere", "extreme"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/coral-reef-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/coral-reef-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/coral-reef-utac/master/README.md",
  },
  {
    name: "biodiversity-utac",
    title: "biodiversity-utac",
    packageNumber: 115,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Andren 1994 (real 30% habitat-remaining fragmentation threshold), Koh et al. 2004 (real coextinction cascade model, 6300 coendangered affiliate species, ~2/3 of 9650 modeled interspecific systems at collapse risk), current IUCN Red List (169,420 assessed / 47,187 threatened) and WWF Living Planet Index 2024 (terrestrial populations down 69%, 1970-2020), and Simkins et al. 2025 (the honesty check: targeted conservation actions produce real positive outcomes even as the aggregate trend worsens). Deliberately no UTAC/CREP/AFET bridge and no invented Gamma value -- see DISCLAIMER.md. GenesisAeon P115.",
    keywords: ["GenesisAeon", "P115", "biodiversity", "extinction", "habitat-fragmentation", "coextinction", "open-science"],
    dois: ["10.2307/3545823", "10.1126/science.1101101", "10.1371/journal.pbio.3003051"],
    selfDoi: null,
    themes: ["biosphaere"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/biodiversity-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/biodiversity-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/biodiversity-utac/master/README.md",
  },
  {
    name: "pollinator-network-utac",
    title: "pollinator-network-utac",
    packageNumber: 116,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "Hallmann et al. 2017 (real Krefeld flying-insect-biomass decline, -76% average over 27 years, 63 protected areas), IPBES 2016 Pollinator Assessment (35% of crop volume pollinator-dependent, USD235-577bn/yr, 300% production-volume growth in 50 years), Vanbergen et al. 2017 (real plant-pollinator network extinction-cascade mechanism), and Valido et al. 2019 (the honesty check: managed honeybees can disrupt wild pollinator networks). Deliberately no UTAC/CREP/AFET bridge and no invented Gamma value -- see DISCLAIMER.md. GenesisAeon P116.",
    keywords: ["GenesisAeon", "P116", "pollinators", "insect-decline", "biodiversity", "food-security", "open-science"],
    dois: ["10.1371/journal.pone.0185809", "10.1111/1365-2435.12823", "10.1038/s41598-019-41271-5"],
    selfDoi: null,
    themes: ["biosphaere", "gesellschaft"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/pollinator-network-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/pollinator-network-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/pollinator-network-utac/master/README.md",
  },
  {
    name: "invasive-species-utac",
    title: "invasive-species-utac",
    packageNumber: 117,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "master",
    abstract: "IPBES 2023 (real, official global invasive-species assessment: USD423bn/yr cost as of 2019, 60% of extinctions invasive-linked, 3500+ harmful of 37000+ introduced species), Marshall 2018 (real, causally-attributed Lake Victoria trophic cascade, 200+ cichlid species lost to introduced Nile perch), and Williamson & Fitter 1996 + Spatz et al. 2022 (the honesty check: most introductions never become invasive per the tens rule, and island eradication succeeds 88% of the time in 1550 real attempts). Deliberately no UTAC/CREP/AFET bridge and no invented Gamma value -- see DISCLAIMER.md. GenesisAeon P117.",
    keywords: ["GenesisAeon", "P117", "invasive-species", "trophic-cascade", "biodiversity", "conservation", "open-science"],
    dois: ["10.5281/zenodo.7430682", "10.1139/cjfas-2017-0056", "10.1038/s41598-022-14982-5"],
    selfDoi: null,
    themes: ["biosphaere"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/invasive-species-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/invasive-species-utac/master/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/invasive-species-utac/master/README.md",
  },
  {
    name: "el-nino-amplification-utac",
    title: "el-nino-amplification-utac",
    packageNumber: 118,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real coral-paleorecord evidence that El Nino events over the last 40 years are ~40% stronger than the pre-industrial millennium baseline (Cole et al. 2026, Science), plus a real complication from the same method extended to ~4000 years before present showing La-Nina-skewed variability (Tripp et al. 2026, GRL). Deliberately no UTAC/CREP/AFET bridge and no invented Gamma value -- see DISCLAIMER.md. GenesisAeon P118.",
    keywords: ["GenesisAeon", "P118", "climate", "El Nino", "ENSO", "paleoclimate", "coral", "open-science"],
    dois: ["10.1126/science.ady2660", "10.1029/2025GL119006"],
    selfDoi: null,
    themes: ["ozean", "biosphaere"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/el-nino-amplification-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/el-nino-amplification-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/el-nino-amplification-utac/main/README.md",
  },
  {
    name: "marine-heatwave-utac",
    title: "marine-heatwave-utac",
    packageNumber: 119,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real marine heatwave frequency (+108%), duration (+63%), and depth-penetration trends for Southeast Asia (2003-2023 vs 1982-2002), plus a real El Nino/Indian Ocean Dipole compounding-effect coupling for the strongest recorded events (Gulakaram et al. 2026, JGR Oceans). Deliberately no UTAC/CREP/AFET bridge and no invented Gamma value -- see DISCLAIMER.md. GenesisAeon P119.",
    keywords: ["GenesisAeon", "P119", "climate", "marine heatwave", "ocean", "El Nino", "open-science"],
    dois: ["10.1029/2025JC023614"],
    selfDoi: null,
    themes: ["ozean", "extreme"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/marine-heatwave-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/marine-heatwave-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/marine-heatwave-utac/main/README.md",
  },
  {
    name: "antarctic-ice-shelf-utac",
    title: "antarctic-ice-shelf-utac",
    packageNumber: 120,
    version: "2.0.0",
    released: "2026-09-03",
    license: "MIT",
    branch: "main",
    abstract: "Real Antarctic ice shelf mass budget (71 of 162 shelves lost mass 1997-2021, 8.3 trillion tonnes total, Davison et al. 2023), a real Holocene meltwater-release feedback mechanism (Nature Geoscience 2025), and a real sign-flipped regional asymmetry under CMIP6 projections -- East Antarctica's feedback amplifies warming, West Antarctica's Amundsen/Bellingshausen sectors show cooling/suppressed warming (Muilwijk et al. 2026, The Cryosphere). v2.0.0 adds six more real, independently verified mechanisms: subglacial hydrology (85 newly detected active lakes, Wilson et al. 2025), the Southern Annular Mode -- where the Arctic 'vortex instability exports cold air' analogy does NOT transfer (Lim et al. 2019, Verfaillie et al. 2022), sea-ice albedo feedback (Riihela et al. 2021), seismic-ice interactions (Wiens et al. 2008), black carbon deposition (Cordero et al. 2022, Magalhaes et al. 2024 -- distinct from P105's Tibetan Plateau focus), and ENSO teleconnection (Paolo et al. 2018, Ayabilah et al. 2026 -- a real, resolved timescale tension with this package's own core finding). Deliberately no UTAC/CREP/AFET bridge and no invented Gamma value -- see DISCLAIMER.md. GenesisAeon P120.",
    keywords: ["GenesisAeon", "P120", "climate", "Antarctica", "ice shelf", "cryosphere", "open-science"],
    dois: ["10.1126/sciadv.adi0186", "10.5194/tc-20-1087-2026", "10.1038/s41467-025-63773-9", "10.1038/s41561-022-01059-1", "10.1038/s43247-022-00458-x", "10.1038/s41561-023-01317-w", "10.1038/s41561-021-00841-x", "10.1038/nature06990", "10.1038/s41467-022-28560-w", "10.1126/sciadv.adp1682", "10.1038/s41561-017-0033-0"],
    selfDoi: null,
    themes: ["kryosphaere", "ozean", "hydrologie", "kohlenstoff"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/antarctic-ice-shelf-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/antarctic-ice-shelf-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/antarctic-ice-shelf-utac/main/README.md",
  },
  {
    name: "wildfire-flood-cascade-utac",
    title: "wildfire-flood-cascade-utac",
    packageNumber: 121,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real fire-season timing shift (regionally divergent, not global), two independent precipitation-intensification mechanisms (smoke-aerosol invigoration, warmer-SST moisture), and three independent flood-severity-amplification mechanisms (post-fire canopy loss, degraded river channels/floodplains, settlement-area sealing). A dedicated synthesis module makes explicit that the full combined cascade is not itself a single directly-studied finding, though every component link is real. Deliberately no UTAC/CREP/AFET bridge and no invented Gamma value -- see DISCLAIMER.md. GenesisAeon P121.",
    keywords: ["GenesisAeon", "P121", "climate", "wildfire", "precipitation", "flood risk", "open-science"],
    dois: ["10.1029/2025GL121153", "10.1126/sciadv.adt2041", "10.1038/s41612-025-01047-3", "10.1038/s41467-026-68929-9", "10.1038/s43247-025-02748-6", "10.1038/s43247-026-03517-9", "10.1016/j.jenvman.2026.129513"],
    selfDoi: null,
    themes: ["atmosphaere", "hydrologie", "extreme"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/wildfire-flood-cascade-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/wildfire-flood-cascade-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/wildfire-flood-cascade-utac/main/README.md",
  },
  {
    name: "ocean-acidification-utac",
    title: "ocean-acidification-utac",
    packageNumber: 122,
    version: "1.0.0",
    released: "2026-09-01",
    license: "MIT",
    branch: "main",
    abstract: "Real ocean acidification planetary-boundary science (Findlay et al. 2025, Global Change Biology: boundary crossed globally, ~40% surface / ~60% subsurface to 200m) including the boundary metric's own active scientific revision (Findlay & Feely 2026, National Science Review: the original 80% threshold doesn't satisfy its own justifying criteria). Deliberately no UTAC/CREP/AFET bridge -- see DISCLAIMER.md. GenesisAeon P122.",
    keywords: ["GenesisAeon", "P122", "climate", "ocean acidification", "planetary boundary", "open-science"],
    dois: ["10.1111/gcb.70238", "10.1093/nsr/nwag173"],
    selfDoi: null,
    themes: ["ozean"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/ocean-acidification-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/ocean-acidification-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/ocean-acidification-utac/main/README.md",
  },
  {
    name: "tropical-glacier-ecosystem-rle-utac",
    title: "tropical-glacier-ecosystem-rle-utac",
    packageNumber: 123,
    version: "1.0.0",
    released: "2026-09-01",
    license: "MIT",
    branch: "main",
    abstract: "Real tropical glacier ecosystem collapse science: the first-ever IUCN Red List of Ecosystems assessment of a tropical glacier ecosystem (Ferrer-Paris et al. 2024, Oryx, DOI 10.1017/S0030605323001771 -- Cordillera de Merida, Venezuela, 90% ice decline, status CR/plausibly already Collapsed) plus an independent East African confirmation (Hinzmann et al. 2024, Environmental Research: Climate, DOI 10.1088/2752-5295/ad1fd7 -- Kilimanjaro/Mount Kenya/Rwenzori). Honesty-check module distinguishes ecosystem-collapse diagnosis from downstream water-security impact. Deliberately no UTAC/CREP/AFET bridge -- see DISCLAIMER.md. GenesisAeon P123.",
    keywords: ["GenesisAeon", "P123", "climate", "glacier", "Red List of Ecosystems", "cryosphere", "open-science"],
    dois: ["10.1017/S0030605323001771", "10.1088/2752-5295/ad1fd7"],
    selfDoi: null,
    themes: ["kryosphaere", "biosphaere", "hydrologie"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/tropical-glacier-ecosystem-rle-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/tropical-glacier-ecosystem-rle-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/tropical-glacier-ecosystem-rle-utac/main/README.md",
  },
  {
    name: "marine-compound-stressors-utac",
    title: "marine-compound-stressors-utac",
    packageNumber: 124,
    version: "1.0.0",
    released: "2026-09-01",
    license: "MIT",
    branch: "main",
    abstract: "Real compound marine-extreme escalation science (Wong et al. 2024, AGU Advances, DOI 10.1029/2023AV001059 -- triple compound extremes expanded 39x/3x/6x since the 1960s), connecting ocean-deoxygenation-utac (P93), coral-reef-utac (P114), and marine-heatwave-utac (P119) via the Metabolic Index (Deutsch et al. 2015, Science, DOI 10.1126/science.aaa1605). Honesty-check module (Moree et al. 2023, Biogeosciences, DOI 10.5194/bg-20-2425-2023): species-specific vulnerability, not raw stress magnitude, explains 85-88% of habitat-loss variance. Deliberately no UTAC/CREP/AFET bridge -- see DISCLAIMER.md. GenesisAeon P124.",
    keywords: ["GenesisAeon", "P124", "climate", "ocean", "compound extremes", "marine ecology", "open-science"],
    dois: ["10.1029/2023AV001059", "10.1126/science.aaa1605", "10.5194/bg-20-2425-2023"],
    selfDoi: null,
    themes: ["ozean", "biosphaere", "extreme"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/marine-compound-stressors-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/marine-compound-stressors-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/marine-compound-stressors-utac/main/README.md",
  },
  {
    name: "assisted-gene-flow-utac",
    title: "assisted-gene-flow-utac",
    packageNumber: 125,
    version: "1.0.0",
    released: "2026-09-01",
    license: "MIT",
    branch: "main",
    abstract: "Real assisted gene flow / coral selective-breeding science: regulatory reform enabling proactive AGF for Caribbean elkhorn coral (Baker et al. 2025, Science, DOI 10.1126/science.adx5842) and real, measured larval heat-tolerance gains up to 2.2-fold (Lago et al. 2025, Proc. R. Soc. B, DOI 10.1098/rspb.2025.1817). Honesty check: the same study finds adult response variable -- whether juvenile gains persist to reproductive adulthood is a genuinely open question. Deliberately corrects an initial outbreeding-depression framing (low risk for corals specifically). Deliberately no UTAC/CREP/AFET bridge -- see DISCLAIMER.md. GenesisAeon P125.",
    keywords: ["GenesisAeon", "P125", "climate", "coral", "assisted gene flow", "conservation genetics", "open-science"],
    dois: ["10.1126/science.adx5842", "10.1098/rspb.2025.1817", "10.1111/ele.12376"],
    selfDoi: null,
    themes: ["ozean", "biosphaere"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/assisted-gene-flow-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/assisted-gene-flow-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/assisted-gene-flow-utac/main/README.md",
  },
  {
    name: "climate-landuse-biodiversity-nexus-utac",
    title: "climate-landuse-biodiversity-nexus-utac",
    packageNumber: 126,
    version: "1.0.0",
    released: "2026-09-01",
    license: "MIT",
    branch: "main",
    abstract: "Real biodiversity-driver ranking science: the official IPBES Nexus Assessment's five direct biodiversity drivers, and a real quantitative synthesis (Jaureguiberry et al. 2022, Science Advances, DOI 10.1126/sciadv.abm9982) finding land/sea-use change dominant on land/freshwater. Relation package connecting amazon-utac (P19), freshwater-ecosystem-stressors-utac (P106), mixed-forest-resilience-utac (P113), and biodiversity-utac (P115) to their respective driving mechanism. Honesty-check: the ranking reverses in the ocean realm. Deliberately no UTAC/CREP/AFET bridge -- see DISCLAIMER.md. GenesisAeon P126.",
    keywords: ["GenesisAeon", "P126", "climate", "biodiversity", "land use", "IPBES", "open-science"],
    dois: ["10.1126/sciadv.abm9982"],
    selfDoi: null,
    themes: ["ozean", "biosphaere", "hydrologie"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/climate-landuse-biodiversity-nexus-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/climate-landuse-biodiversity-nexus-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/climate-landuse-biodiversity-nexus-utac/main/README.md",
  },
  {
    name: "arctic-climate-utac",
    title: "arctic-climate-utac",
    packageNumber: 127,
    version: "1.0.0",
    released: "2026-09-03",
    license: "MIT",
    branch: "main",
    abstract: "Six real, independently verified Arctic climate mechanisms: sea-ice albedo feedback (Duspayev et al. 2024, Zhang et al. 2025), Greenland ice sheet mass balance (IMBIE Team 2020, Khan et al. 2014 -- a genuinely different mechanism balance than Antarctica's ocean-driven-basal-melt-dominant picture), permafrost carbon feedback (Schuur et al. 2015, Turetsky et al. 2020, Natali et al. 2019/2025), the genuinely contested Arctic-amplification/jet-stream cold-outbreak link (Cohen et al. 2021 vs. Blackport & Screen 2020, presented as a live scientific debate, not resolved), black carbon deposition (Cho et al. 2025), and Arctic Ocean acidification / East Siberian Arctic Shelf methane (Yamamoto-Kawai et al. 2009, Robbins et al. 2013, Steinbach et al. 2021). Sibling package to antarctic-ice-shelf-utac (P120), built the same way. Deliberately no UTAC/CREP/AFET bridge and no invented Gamma value -- see DISCLAIMER.md. GenesisAeon P127.",
    keywords: ["GenesisAeon", "P127", "climate", "Arctic", "cryosphere", "permafrost", "sea ice", "open-science"],
    dois: [
      "10.1029/2024GL109608",
      "10.5194/tc-19-6807-2025",
      "10.1038/s41586-019-1855-2",
      "10.1038/NCLIMATE2161",
      "10.1038/nature14338",
      "10.1038/s41561-019-0526-0",
      "10.1038/s41558-019-0592-8",
      "10.1038/s41558-024-02234-5",
      "10.1126/science.abi9167",
      "10.1126/sciadv.aay2880",
      "10.1088/2752-5295/ad93f3",
      "10.1016/j.scitotenv.2025.178423",
      "10.1126/science.1174190",
      "10.1371/journal.pone.0073796",
      "10.1073/pnas.2019672118",
    ],
    selfDoi: null,
    themes: ["kryosphaere", "ozean", "atmosphaere", "kohlenstoff"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/arctic-climate-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/arctic-climate-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/arctic-climate-utac/main/README.md",
  },
  {
    name: "polar-biodiversity-utac",
    title: "polar-biodiversity-utac",
    packageNumber: 128,
    version: "1.0.0",
    released: "2026-09-03",
    license: "MIT",
    branch: "main",
    abstract: "Real polar biodiversity trends across both poles, broad-spectrum with a deliberate focus on penguins, polar bears, and whales: penguin species trends (Fretwell et al. 2023, Strycker et al. 2020 -- Gentoo expands while Adelie/Chinstrap decline in the same region), polar bear subpopulation status (IUCN/PBSG: 2 of 19 increasing, 5 stable; Archer et al. 2025, Dunham et al. 2024), whale recovery and new threats (Zerbini et al. 2019: humpback recovered to 93% of pre-exploitation abundance; Savoca et al. 2024: krill-fishery tension), the krill/zooplankton/phytoplankton food-web base (Atkinson et al. 2019, Lewis et al. 2020), seals/seabirds/walrus (Dunn et al. 2025, Clay et al. 2025), and terrestrial biodiversity shifts (Roland et al. 2024, Tyler 2010, Corso et al. 2022). Third sibling package to antarctic-ice-shelf-utac (P120) and arctic-climate-utac (P127), built the same way. Deliberately no UTAC/CREP/AFET bridge and no invented Gamma value -- see DISCLAIMER.md. GenesisAeon P128.",
    keywords: ["GenesisAeon", "P128", "climate", "biodiversity", "Antarctica", "Arctic", "penguins", "polar bears", "whales", "open-science"],
    dois: [
      "10.1038/s43247-023-00927-x",
      "10.1038/s41598-020-76479-3",
      "10.1126/science.adp3752",
      "10.1890/14-1129.1",
      "10.1111/mms.13107",
      "10.1098/rsos.190368",
      "10.1038/s41467-024-51954-x",
      "10.1002/jwmg.22657",
      "10.1038/s41558-018-0370-z",
      "10.1093/icesjms/fsaf049",
      "10.1111/gcb.15937",
      "10.1126/science.aay8380",
      "10.1007/s00300-016-2023-x",
      "10.1111/gcb.70290",
      "10.1126/sciadv.abh3674",
      "10.1111/cobi.70126",
      "10.1038/s41561-024-01564-5",
      "10.1890/09-1070.1",
      "10.1038/s42003-022-03042-3",
    ],
    selfDoi: null,
    themes: ["biosphaere", "ozean", "kryosphaere"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/polar-biodiversity-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/polar-biodiversity-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/polar-biodiversity-utac/main/README.md",
  },
  {
    name: "resilience-memory-utac",
    title: "resilience-memory-utac",
    packageNumber: 97,
    version: "1.0.1",
    released: "2026-08-31",
    license: "MIT",
    branch: "main",
    abstract: "Real critical-slowing-down early-warning statistics (Dakos et al. 2012, Scheffer et al. 2009, Dakos et al. 2008) and post-perturbation resilience-debt tracking (van Nes & Scheffer 2007). Deliberately no UTAC/CREP/AFET bridge. GenesisAeon P97.",
    keywords: ["GenesisAeon", "P97", "resilience", "critical-slowing-down", "early-warning-signals", "open-science"],
    dois: [],
    selfDoi: "10.5281/zenodo.21821795",
    themes: ["extreme"] as ClimatePackage["themes"],
    noUtacBridge: true,
    htmlUrl: "https://github.com/GenesisAeon/resilience-memory-utac",
    citationUrl: "https://raw.githubusercontent.com/GenesisAeon/resilience-memory-utac/main/CITATION.cff",
    readmeUrl: "https://raw.githubusercontent.com/GenesisAeon/resilience-memory-utac/main/README.md",
  },
];
